name: chronomancer
description: A build planner for the video game Chronicon
version: 1.3.0
homepage: https://github.com/iconmaster5326/Chronomancer

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  http: ^0.12.2
  stream_transform: ^1.2.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
